(setq slovarik-conjunctions [
"и"
"где"
"как"
"да"
"всё-таки"
"но"
"или"
"али"
"же"
"ведь"
"что"
"што"
"кто"
"когда"
"ли"
"потому что"
"если"
"чтобы"
"чтоб"
"раз"
"чем"
"ни"
"п.т.ч."
"либо"
"пока"
"пока не"
"то"
"поскольку"
"хотя"
"так как"
"ль"
"после того как"
"ибо"
"дабы"
"правда"
"точно"
"абы"
"благо"
"еслибы"
"настолько"
"будто"
"нежели"
"не говоря уже о"
"коли"
"словно"
"пусть"
"тогда как"
"с тех пор как"
"ежели"
"хто"
"в то время как"
"причём"
"ровно"
"иль"
"а то"
"почём"
"в результате"
"в итоге"
"что касается"
"как будто"
"если только"
"покуда"
"до тех пор пока"
"несмотря на то, что"
"а также"
"до сих пор"
"хотя бы"
"если бы"
"перед тем как"
"до того как"
"как бы не"
"лишь только"
"только лишь"
"по мере того как"
"благодаря тому, что"
"благодаря чему"
"в результате чего"
"из-за того, что"
"так что"
"словно бы"
"коль"
"пускай"
"кабы"
"яко"
"поелику"
"то ли"
"newWord"
])


(setq slovarik-conjunctions-defs [

"and, as well as, both ... and ..., as well, even"
"where"
"how, what, like, as"
"and (сочинительный, соединительный союз!-- should this not read 'coordinating conjunction'? --), but"
"and again, and yet, however, yet ''(reinforcing something)''"
"but, yet"
"or, or else, either"
"{old|colloquial} or"
"{contrasting} and, but, whereas, as for, as to"
"you see, you know"
"that"
"{misspelling of|что}"
"who"
"when"
"whether, if"
"because"
"if, in case"
"that...should ({n-g|indicates the subjunctive}), so that, in order that; in order to, lest"
"{alternative form of|что́бы}"
"{colloquial} if, since; as long as"
"than, instead of, rather"
"neither, nor"
"{ru-initialism of|потому́ что||because}"
"either...or"
"so long as, while"
"unless, until"
"then"
"inasmuch as, as, since"
"although, though {qualifier|contrasting two clauses}"
"as, since, inasmuch as"
"{alternative form of|ли}"
"after"
"{literary} for, because, as, since"
"{archaic|non-standard colloquial} in order to, in order that, so that"
"though, however, but, admittedly"
"as though, as if"
"so that, if only"
"{colloquial} since, now that, {colloquial} the more so because"
"{dated|non-standard} a nonstandard or dated spelling of {l|е́сли бы}"
"as"
"as if, as though, allegedly, that (with some uncertainty)"
"{dated} than"
"let alone, to say nothing of"
"{obsolete} if (supposing that), {obsolete} when"
"like, as if, as it were"
"though, even (if), although, {mathematics} let"
"whereas (but in contrast; whilst on the contrary…)"
"since"
"{obsolete|colloquial} if, in case"
"{proscribed|low|_|colloquial|non-standard|Ukraine|Belarus|South Russia} who, non-standard form of {m|кто}"
"while, whereas, when"
"moreover, and, at that, with"
"{vernacular} as if, as though, like (expresses an uncertain assumption)"
"{poetic} ''a shortened version of'' '''{l|и́ли}''': or, or else, either"
"otherwise"
"how"
"as a result {consequently}"
"as a result {consequently}"
"as for, as to {regarding; about}"
"as if, as though, like, as"
"provided, provided that, providing, as long as {if, assuming}, sobeit"
"as long as, while, whilst"
"until, till, so long as, as long as, as {while}"
"although, in spite of the fact that, despite the fact that"
"as well as {and in addition}"
"as yet"
"though, even if, even though, if only"
"if (only)"
"before"
"before, till"
"that; lest {qualifier|implying emotional negativity towards an event that would happen in a possible future or that already happened in the past}"
"as soon as, just as"
"{form of|alternative form|лишь то́лько}"
"as"
"thanks to the fact that"
"so (has a literary sense)"
"{literary} therefore, as a result"
"because"
"so, so that"
"{alternative form of|сло́вно}"
"{alternative form of|ко́ли}"
"''same as'' {l|пусть}"
"{colloquial} if, if only"
"{dated} like, as, {dated} for, because"
"{archaic} because, inasmuch as"
"maybe…or maybe; either…or {q|of an uncertain or unclear choice between possibilities}"
"newWord means this and that"
"newWord means this and that"
])

