(setq slovarik-interjections [

"а"
"е"
"ы"
"э"
"будь здоров"
"да"
"чай"
"спасибо"
"прикол"
"добро пожаловать"
"мяу"
"это"
"слава богу"
"класс"
"гей"
"но"
"сука"
"есть"
"ведь"
"алло"
"до свидания"
"вот"
"еб"
"привет"
"гм"
"и-го-го"
"му"
"бэ-бэ"
"хрю"
"гав-гав"
"ав-ав"
"тяв-тяв"
"мур"
"бе-бе"
"куд-куд-кудах"
"кудах-кудах"
"кукареку"
"кря-кря"
"га-га-га"
"чик-чирик"
"ку-ку"
"квак"
"ж-ж-ж"
"шутка"
"ну"
"тпру"
"круто"
"супер"
"с днем рождения"
"поздравляю с днем рождения"
"ай"
"айда"
"пока"
"ебать"
"черт"
"то-то"
"помогите"
"на помощь"
"на подмогу"
"пожалуйста"
"большое спасибо"
"кругом"
"прием"
"марш"
"с Новым годом"
"вон"
"тс-с-с"
"уф"
"фу"
"фу-фу"
"м-м-да"
"эй"
"ай-ай-ай"
"ш-ш-ш"
"бр-р"
"здорово"
"тьфу"
"и точка"
"не за что"
"еще бы"
"мотор"
"пиздец"
"ч. т. д."
"блядь"
"но-о-о"
"да-с"
"внимание"
"земля видна"
"молоток"
"вот это да"
"кар"
"цап"
"приятного аппетита"
"назад"
"так-с"
"слушаю-с"
"хм"
"бегом"
"удачи"
"молодец"
"фи"
"точка"
"молодца"
"пру"
"честное слово"
"да-а"
"увы"
"ша"
"ст"
"цыц"
"тише"
"правда"
"здравствуйте"
"здравствуй"
"добрый день"
"привѣтъ"
"ага"
"блин"
"пошел"
"аллилуйя"
"аминь"
"точно"
"топ"
"руки вверх"
"эврика"
"проклятие"
"очень приятно"
"аба"
"прости"
"поехали"
"осторожно"
"однако"
"кы-кы"
"давай"
"доброе утро"
"пошел на хуй"
"добрый вечер"
"спокойной ночи"
"на здоровье"
"заебись"
"хо"
"именно"
"ладно"
"дьявол"
"фак"
"пять баллов"
"окей"
"бум"
"не так ли"
"не правда ли"
"не-а"
"не'а"
"угу"
"ту"
"браво"
"але"
"зараза"
"шлеп"
"тихо"
"чудесно"
"бля"
"бай-бай"
"короче"
"спокойно"
"хуй тебе"
"жесть"
"чур"
"щелк"
"ох"
"до скорого"
"мастдай"
"стоп"
"давайте"
"спасите"
"чух"
"ау"
"будьте здоровы"
"ура"
"и-а"
"итак"
"еб твою мать"
"Господи"
"жалко"
"серьезно"
"горько"
"ей-богу"
"оп-пля"
"каков"
"доброго пути"
"счастливого пути"
"э-э-э"
"клево"
"е-мое"
"е мое"
"о-го-го"
"Веселого Рождества"
"Счастливого Рождества"
"ого"
"не стоит благодарности"
"приятно познакомиться"
"боже мой"
"о боже"
"увидимся"
"прочь"
"чего"
"о боже мой"
"ква"
"апчхи"
"прощайте"
"прощай"
"баста"
"всего хорошего"
"всего доброго"
"всего наилучшего"
"за ваше здоровье"
"за твое здоровье"
"будем здоровы"
"ваше здоровье"
"пей до дна"
"за здоровье"
"Аллах акбар"
"Аллаху акбар"
"все наверх"
"вольно"
"до встречи"
"с богом"
"чао"
"полно"
"молодчина"
"иншаллах"
"иншааллах"
"караул"
"бабах"
"бах"
"трах"
"бам"
"ба-бах"
"вау"
"упс"
"ауч"
"счастливо"
"потрясающе"
"с легким паром"
"скатертью дорога"
"до скорой встречи"
"абба"
"свистать всех наверх"
"до свиданья"
"бай"
"мерси"
"пардон"
"но пасаран"
"благодарю"
"мля"
"приветик"
"здрасте"
"господи"
"ну да"
"слышь"
"салям алейкум"
"салам алейкум"
"абанамат"
"охуеть"
"блеать"
"смирно"
"салют"
"шалом"
"ради бога"
"сорри"
"как бы не так"
"покороче"
"глядь"
"так точно"
"брысь"
"тук-тук"
"брось"
"кыш"
"ня"
"ну-ка"
"ха-ха"
"вира"
"динь-динь-динь"
"э-э"
"неважно"
"ух"
"да ну"
"вишь"
"ишь"
"пиф-паф"
"проклятье"
"сори"
"а-а"
"игого"
"лады"
"хуя"
"прыг-скок"
"ха-ха-ха"
"отставить"
"пипец"
"а-а-а"
"застрелиться"
"короче говоря"
"м-м"
"ок"
"буль-буль"
"о-о"
"оп"
"нате"
"м-да"
"тсс"
"тьфу-тьфу-тьфу"
"черт побери"
"черт возьми"
"это самое"
"блять"
"адье"
"елки-палки"
"фас"
"одну минуточку"
"секундочку"
"доброго времени суток"
"будьте добры"
"поебать"
"плиз"
"ничего себе"
"ни хуя себе"
"ебанный в рот"
"кек"
"чирк"
"оба-на"
"хуясе"
"с приездом"
"с праздником"
"офигеть"
"охренеть"
"пли"
"звяк"
"хахаха"
"никак нет"
"будь другом"
])


(setq slovarik-interjections-defs [

"oh! {expressing surprise or realization}"
"{slang} yeah!, yo!, oh yeah!"
"{Internet slang} lol, used to express laughter. Usually used as 'ы-ы-ы', to show the crying sound you make after you were laughing for too long., {Internet slang} ы? ''as a closing clause'': Understand? Agree?"
"hey; {n-g|an exclamation to get attention}, {n-g|to indicate doubt, disgust}, {n-g|to clearly indicate a protest or reprimand}, well, uh; {n-g|space filler or pause during conversation}"
"{informal|to a man/boy} gesundheit!, bless you!, {informal|to a man/boy} goodbye|good-bye (lit., 'be healthy'), take care"
"really, yes (''used to confirm that the person being addressed is listening'')"
"methinks, must be, may be, hopefully, probably"
"thank you, thanks (for ... = за ''+ accusative case'')"
"{popular speech} not bad!"
"welcome!"
"{qualifier|imitative} meow (sound a cat makes)"
"uh, er, erm, umm; used in hesitant speech"
"thank God!; thank goodness!"
"{informal} great!"
"hey!, hi!, giddyup!"
"same as {l|но́-о-о}"
"{vulgar} shit!, fuck!"
"all right, okay, right, roger, {military} yessir!, {nautical} aye|aye-aye!"
"after all, indeed, surely, why, well, then, you know, you see, isn’t it?"
"{telephone} {l|en|hello}!"
"goodbye, see you later"
"here, look (at it), take it! (when offering something, casual)"
"|ёб| {vulgar} fuck!"
"{informal} {l|en|hello}"
"{alternative form of|хм}"
"{qualifier|imitative} whinny, neigh (sound a horse makes)"
"{qualifier|imitative} moo (sound a cow makes)"
"{qualifier|imitative} baa (sound a sheep makes)"
"{qualifier|imitative} oink (sound a pig makes)"
"{qualifier|imitative} woof, arf (sound a dog makes)"
"{qualifier|imitative} woof, arf (sound a dog makes)"
"{qualifier|imitative} bow-wow, yap, yip (sound a pup makes)"
"{imitative} purr (sound a contented cat makes)"
"{imitative} baa (sound a sheep makes)"
"{imitative} cluck (sound a chicken makes)"
"{imitative} cluck (sound a chicken makes)"
"{imitative} cock-a-doodle-doo (sound a rooster makes)"
"{qualifier|imitative} quack (sound a duck makes)"
"{imitative} honk (sound a goose makes)"
"{imitative} chirp (sound a bird makes)"
"{onomatopoeia} cuckoo (sound a cuckoo makes), {familiar} hey, {familiar} gotcha; a reaction during hide and seek or peekaboo game"
"croak, ribbit: {non-gloss definition|an imitation of the sound made by a frog.}"
"{onomatopoeia|imitative} buzz, bzz (sound a bee or fly makes)"
"I’m kid|kidding!"
"well"
"whoa (''when commanding a horse or imitative thereof'')"
"{colloquial} cool, awesome"
"{slang} great! super! cool!"
"|с днём рождения| happy birthday"
"|поздравляю с днём рождения| happy birthday"
"ouch! (it hurts!)"
"{colloquial} let's go, c'mon, {colloquial} made off; dashed away; vanished"
"bye; so long; I’ll see you later; see you soon."
"{vulgar} expressing surprise"
"|чёрт| damn!, hell!"
"{colloquial} Aha!, That's it!, There we go! What did I tell you?"
"help#Interjection|help!"
"{l|en|help!}"
"help#Interjection|help!"
"please, you're welcome, not at all, don't mention it, it's a pleasure (reply to thank you), here you are (''when handing something over'')"
"many thanks, thank you very much"
"''(military command)'' about turn, about face"
"|приём| {ham radio} over#Interjection|over, do you copy?"
"forward! (command)"
"Happy New Year"
"out, get out!"
"psst! (listen to this!), shhh!, shh! (quiet!)"
"phew! {I’m tired!}, oof {sound of pain}"
"pew!, ew!, yuck! (it stinks!), aw! (mild disappointment), ''(a command for a dog)'' stop that!, don't do that!"
"pew!, P U!, pee-you! (it stinks!)"
"{alternative form of|м-да́}"
"hey! (you, there!)"
"tsk tsk! (shame on you!)"
"shhh!, shh! (quiet!)"
"{colloquial} brr!, brrr! (it’s cold!), {colloquial} ew (expresses disgust)"
"{colloquial} great!, well done, {colloquial} hi!; hello!"
"{n-g|Mimics the sound of spitting.}, ''(strong disgust or disappointment)'' fie!; for shame!; nuts!; damn|damn it!, dammit!"
"{emphatic} period!, and nothing else!, and nothing less!"
"{&lit|не|за|что}, you're welcome, not at all, don't mention it, not worth mentioning, nothing to speak of, no problem"
"|ещё бы| of course, sure, to be sure, {sarcastic} I'll say, absolutely not"
"{cinematography} action!"
"{vulgar} fucking hell!, holy shit!, what the fuck!"
"QED"
"{vulgar} ''interjection'' (may be contracted to {m|бля}); compare shit!, fuck!, etc., {vulgar|intensive} (may be contracted to {m|бля}); compare damn, fucking, etc., {vulgar} {w|discourse particle}"
"giddyup {qualifier|in urging a horse forward}"
"{obsolete} yes, milord, {obsolete} yes, milady"
"attention! ''(also military)''"
"{nautical} land ahoy"
"{colloquial} nice one!, well done!"
"wow ''(expression of astonishment)''"
"caw ''cry of a crow or raven''"
"snap"
"bon appétit!"
"get back"
"{obsolete} yes, sir, {obsolete} yes, ma'am"
"{obsolete} at your service, milord, {obsolete} at your service, milady"
"hmm, hum"
"run!"
"good luck!"
"attaboy!, attagirl!, well done!"
"{non-gloss definition|Used to show (usually arrogant) lack of admiration, interest, or inspiration}: meh, whatever, {non-gloss definition|Used to show (usually arrogant) disapproval, discontent}: yuck, bah, pah, pfft (same as фу)"
"enough!"
"{slang|rare} {alternative form of|молодец|молоде́ц!}"
"whoa (''when commanding a horse or imitative thereof'')"
"word of honor!, on my word of honor!, honestly, frankly"
"hey {qualifier|expressing pleasant surprise}"
"alas!"
"{slang} shush!, shhh! (be quiet!), {slang} what!? (''surprise, indignation, disgust, excitement or just arrogance'') (''spoken in Odessa, also in multiple other contexts'')"
"shhh!, silence!, be still!"
"{regional|often implies impolite tone} shut up!"
"silence!"
"sure enough, indeed, actually, as a matter of fact, in point of fact, {interrogative} is that so?"
"{formal} hello"
"{informal} hello"
"good day, good afternoon"
"{ru-pre-reform|приве́т}"
"yep, yeah (colloquial form of yes), aha, uh-huh (indicates that the speaker is '''listening''' to you, but does not necessarily imply agreement)"
"{euphemistic|colloquial|exclamation} shoot#Interjection|shoot! (expression of any strong emotion, euphemism for блядь!)"
"|пошёл| begone!, go away! (''to a man'')"
"hallelujah"
"amen"
"exactly!, yes!, bingo!"
"stamp {sound of stamping when walking}"
"hands up!"
"eureka!"
"dammit!, damnation! (expressing strong negative emotions)"
"pleased to meet you (literally: very pleasant)"
"{dialectal|Ural} well, I never|Well, I never! (expression of surprise)"
"sorry, excuse me"
"{slang} let's go|Let's go!, {slang} Let's do it!"
"look out!, look sharp!, watch out!, be careful!, beware, danger!"
"you don't say!, not really!"
"{imitative} sound a swan makes"
"let's, come on, c'mon, {label|very|_|informal} good bye, see you"
"good morning"
"|пошёл на хуй| {vulgar} fuck off|Fuck off! (to a man; replace with 'пошла́' - to a woman and 'пошли́' - to a group)"
"good evening"
"good night"
"to your heart's content, you're welcome (in answer to a thanks for food or refreshments), do as you want at your own risk, be my guest (sarcastically)"
"{vulgar} fucking excellent!"
"ha {expressing laughter}, {n-g|expressing surprise, irony, regret, or admiration}, {rfdef|ru}"
"indeed, rather; used to emphasize the agreement or confirmation."
"well, all right, okay"
"dammit"
"{vulgar|slang} fuck!"
"{slang} excellent! (literally, ''five points''; the same as A grade in U.S. schools)"
"OK, okay"
"thud, crash"
"right; isn't it so?, used as an expression of affirmation after a statement"
"isn't it so? {used as an expression of affirmation after a statement}"
"{colloquial} nuh-uh, nope"
"{alternative spelling of|не́-а}"
"uh-huh, yep, yeah (colloquial form of yes)"
"{onomatopoeia} {n-g|the sound of a train horn}"
"bravo!"
"|алё| {alt form|алло́}"
"damn it"
"|шлёп| flop, smack, plop, splash"
"be quiet!"
"wonderful!, marvelous!, {rfdef|ru}"
"{vulgar} {alternative form of|блядь}"
"hushaby; used when putting a baby to sleep., {slang} bye-bye"
"{potentially|_|vulgar|colloquial} right; signpost word to change the subject in a discussion or discourse, {vulgar|_|when opponent finished his speech} a request to repeat statement in layman's terms; without fuss or needless words, {vulgar|_|when opponent not finished his speech} a request to shorten speech drastically; to conclude immediately"
"quiet!"
"{obscene} '''хуй#Russian|хуй ты#Russian|тебе''' (xuj tebé), go fuck yourself!, fuck you!, go fly a kite!"
"{n-g|Used in surprise, or denoting something horrific.}"
"{colloquial|in spells} avaunt, away, {qualifier|children's talk, expresses leadership, claim to be the first} bags (it)! (British), dibs, {colloquial|expresses a condition} mind you, but mind"
"|щёлк| click (sound of a click)"
"oh, ah"
"see you soon"
"{computing|_|slang} {non-gloss definition|used to express negative attitude towards something}"
"stop!, {colloquial, rare} that'll do, enough"
"let us, let's"
"help!"
"{n-g|the sound of a locomotive}, choo, {n-g|used to drive swine}, sooey|soo wee"
"hello? (is anyone there?)"
"{formal|or|to a group} bless you (said to somebody who has sneezed), {formal|or|to a group} goodbye|good-bye (lit., 'be healthy'), take care"
"hoorah, hooray {elated expression of approval, especially as a battle cry}, yay {expression of happiness}"
"(''imitative'') hee-haw (sound a donkey makes)"
"so, then"
"|ёб твою мать| {idiomatic|vulgar} motherfuck, fuckshit; extremely intense vulgar interjection, more intense than just ''твою́ ма́ть'', used to exclaim peeve, dismay or anger as well as awe or astonishment."
"oh my God, oh my Lord"
"sorry, it is a pity, unfortunately"
"|серьёзно| indeed, really"
"bitter! (''an old Russian tradition: a shout by wedding guests urging the newlyweds to kiss, thus removing the 'bitterness''')"
"really!; really and truly!; honest to God!"
"whoops!; oops! ''(as when stumbling and almost tripping or almost stepping on something to be avoided)'', alley-oop ''(also used as an exclamation when dogs do tricks)''"
"just look! (at him)"
"bon voyage!"
"bon voyage!"
"{alternative spelling of|э}"
"|клёво| cool!, fantastic!"
"|ё-моё| {colloquial} {alternative spelling of|ё моё}"
"|ё моё| {colloquial} ''Expresses disappointment or surprise. {euphemistic form of|ёб твою́ мать}''"
"oh, ho, ho!; wow!; oh, my goodness!; oh, oh, oh! (expresses surprise, admiration, approval, etc.)"
"|Весёлого Рождества| Merry Christmas"
"Merry Christmas"
"whoa; oh, ho!; wow!; oh, my goodness!; oh, oh! (expresses surprise, admiration, approval, etc.)"
"you're welcome, not at all, don't mention it"
"pleased to meet you"
"oh my God|oh my God!"
"oh my God|oh my God!"
"see you later"
"be off, get out, begone, away with you, beat it, scat, hence"
"do what?"
"oh my God|oh my God!, oh God|oh God!"
"croak, ribbit: {non-gloss definition|an imitation of the sound made by a frog.}"
"achoo {the sound of a sneeze}"
"farewell, adieu, good-bye {said to wish a fond farewell; good-bye} {qualifier|formal or to a group of people}"
"farewell, adieu, good-bye {said to wish a fond farewell; good-bye} {qualifier|informal to one person}"
"basta {that's enough, stop}"
"all the best {good luck}"
"all the best {good luck}"
"all the best {good luck}"
"cheers! {toast when drinking, formal, lit.: to your health!}"
"|за твоё здоровье| cheers! {toast when drinking, informal, lit.: to your health!}"
"cheers! {toast when drinking}"
"cheers! {toast when drinking}"
"{colloquial} bottoms up!, cheers! {lit., ''drink to the bottom!''}"
"cheers {toast when drinking, generic but less common}"
"{Islam} Allahu akbar, Allah akbar {Muslim takbir - proclamation}"
"{Islam} Allahu akbar, Allah akbar {Muslim takbir - proclamation}"
"all hands on deck! {order}"
"{military} at ease"
"see you (later), goodbye {farewell}"
"God be with you!, God go with you, speed!, God be your help!, success attend you!, good luck!, here goes!"
"goodbye {farewell}, ciao"
"okay, stop, that's it, enough (of this)"
"attaboy!, attagirl!, well done!, fine fellow!, good boy!, good girl!, etc. {used to show encouragement or approval to a male or female}"
"{Islam} inshallah {God willing}"
"{Islam} inshallah {God willing}"
"help!"
"kaboom {sound of an explosion}"
"kaboom {sound of an explosion}"
"bang {verbal percussive sound}"
"bang {verbal percussive sound}"
"kaboom {sound of an explosion}"
"wow {excitement}"
"oops {acknowledging a minor mistake}"
"{neologism} ouch {expression of one's own physical pain}"
"{non-gloss definition|An informal farewell.}"
"awesome!, super!"
"|с лёгким паром| {qualifier|lit.: “with a light steam”} {a friendly remark made to someone who's just come from the bath}"
"good riddance|good riddance! {used to indicate that loss is welcome, lit.: let the road be like a tablecloth}"
"see you soon {goodbye}"
"{dialectal} {alternative spelling of|аба#Etymology_2|аба́||interjection of surprise}"
"all hands on deck {order}"
"{alternative spelling of|до свида́ния}"
"{colloquial} bye"
"{colloquial} thank you"
"{colloquial} sorry, excuse me"
"{colloquial} no pasarán {slogan, 'they shall not pass'}"
"thanks! {qualifier|conversational}"
"{euphemistic form of|бля}"
"{informal} hi, hey"
"{colloquial} hi, hello, howdy, abbreviated form of {l|здра́вствуйте}"
"{alternative case form of|Го́споди}"
"{sarcastic} yeah right, get off with you! (disbelief), well, yes; sure"
"hey! {i|literally 'do you hear'}"
"{Islam} {l|en|salaam alaikum} {q|Muslim greeting}"
"{alt form|саля́м але́йкум}"
"{slang|vulgar|humorous} Expression of annoyance or frustration."
"{vulgar} fucking hell!, holy shit!, what the fuck!"
"{slang|emphatic} {eye dialect of|блядь}"
"{military} attention! {non-gloss definition|Used as a command to bring soldiers to the attention position}."
"{informal} hello, {informal} bye"
"shalom {transliteration of the Jewish greeting or farewell}"
"for God's sake {exclamation of surprise, impatience, etc.}, by all means, please, feel free, of course, go ahead"
"{slang} sorry"
"as if; not likely"
"make it snappy"
"lo and behold!"
"{informal|or|military} yessir; positive"
"shoo! (to make something go away)"
"knock-knock {verbal knocking sound}"
"stop it!, pack it in! quit it!"
"shoo! (especially to a cat)"
"{rfdef|ru}"
"now!, come!, come on!, well, let's see"
"ha-ha"
"{slang} lift!"
"ding dong (onomatopoeia for the sound of a doorbell)"
"{alternative spelling of|э}"
"it doesn't matter, it's OK"
"ooh!, gosh!, oof!"
"{sarcastic} yeah right, get off with you! (disbelief)"
"{colloquial} see!; (just) look, listen; there; oh; now"
"{colloquial} see!; (just) look, listen; there; oh; now"
"{onomatopoeia} rat-a-tat-tat (the sound of gunshots)"
"{alternative form of|прокля́тие|nocap=1}"
"{slang} sorry"
"ah, aah, oh (expressing understanding or realisation), aah (a cry of horror, the sound of screaming)"
"{qualifier|imitative} whinny, neigh (imitates the sound of a horse neighing)"
"same as ладно"
"{vulgar} {ellipsis of|ни хуя́ (себе́)|nodot=1}: holy shit"
"{n-g|Used to describe or encourage jumping and skipping.}"
"ha ha {sound of laughter}"
"{military} as you were!"
"{euphemism|vulgar} hell!, euphemism for {m|пизде́ц}"
"{alternative form of|а́-а}"
"{low|_|colloquial} what a blast!, it's a screamer!, it's enough to drive you mad!, I'll be damned!"
"{colloquial} right; signpost word to change the subject in a discussion or discourse"
"uh, um {expressing hesitation in speech}"
"{n-g|Same as Окей but used as a slang, especially by younger generation.}, {rfdef|ru}"
"{n-g|Represents the sound of liquid bubbling or gurgling.}"
"{colloquial} ow, uh-oh {expressing fear}, golly {expressing surprise}, {rfdef|ru}"
"oops, {rfdef|ru}"
"{colloquial} (''an exclamation of surprise'')"
"pff"
"psst! (listen to this!), shhh!, shh! (quiet!) hush"
"knock on wood ({n-g|said to void a jinx}), {elliptical} {n-g|Implies something positive, or a hope for something positive.}"
"|чёрт побери| {colloquial} damn!, dammit! {expression of anger or disappointment}"
"|чёрт возьми| {colloquial} damn!, dammit! {expression of anger or disappointment}"
"{n-g|A space filler in conversation.}"
"{vulgar} fuck, shit, damn, {vulgar|intensive} compare fucking and damn"
"|адьё| {colloquial|dated} adieu {farewell}"
"|ёлки-палки| {colloquial} fiddlesticks! {expression of mild dismay or annoyance}"
"''(a command to a dog)'' attack!, get'em!, bite!"
"wait a moment, {now|_|rare} right {i|especially as first words in the sentence}"
"wait a moment, stop!, {now|_|rare} right (especially as first words in the sentence)"
"{sometimes|humorous|Internet|_|slang} good morning {non-gloss definition|Used as a greeting when meeting somebody for the first time in the morning.}, {sometimes|humorous|Internet|_|slang} good evening {non-gloss definition|Used as a greeting in the evening}., {sometimes|humorous|Internet|_|slang} good afternoon; a greeting said when meeting somebody in the afternoon., {sometimes|humorous|Internet|_|slang} good day {dated|formal} {non-gloss definition|A somewhat formal greeting generally used between sunrise and sunset.}, {internet|hypercorrect} good whatever time of day"
"{formal|or|to a group} please, would you be so kind"
"{vulgar} (somebody) doesn't give a fuck"
"{slang|rare} please"
"{colloquial} wow!"
"{vulgar} wow!; fucking hell!"
"|ёбанный в рот| {vulgar} fucking hell!"
"{Internet slang} kek"
"{colloquial} fwoosh {the sound of a match being struck}"
"{colloquial} ''used to express surprise, typically also implying content or irony''"
"{vulgar} what the fuck !--or one book glosses it as: holy shit --"
"happy arrival!, welcome!"
"happy holiday! {a generic phrase used on various types of national or public holidays}"
"{mildly|_|vulgar} frick!, holy shit!, {mildly|_|vulgar|used as an adverb} freaking, fricking"
"{vulgar} what the hell!, holy shit!"
"{obsolete} fire!"
"plink, bang {sound}"
"ха-ха-ха"
"{military} no sir; negative"
"{informal} please"
])

