(setq slovarik-predicatives [

"о"
"с"
"в"
"у"
"по"
"со"
"ко"
"для"
"из"
"об"
"во"
"на"
"до"
"от"
"без"
"после"
"под"
"против"
"вм."
"вкл."
"в т. ч."
"ок."
"из-за"
"за"
"около"
"прежде"
"через"
"близ"
"вместо"
"мимо"
"возле"
"кроме"
"вокруг"
"вдоль"
"внутри"
"вопреки"
"из-под"
"вне"
"между"
"меж"
"над"
"надо"
"среди"
"средь"
"позади"
"подле"
"ради"
"сверх"
"сквозь"
"перед"
"передо"
"пред"
"предо"
"посреди"
"про"
"при"
"подо"
"кругом"
"супротив"
"напротив"
"насупротив"
"вследствие"
"по отношению к"
"включая"
"назад"
"ото"
"съ"
"подъ"
"къ"
"въ"
"надъ"
"объ"
"отъ"
"благодаря"
"согласно"
"изо"
"посредством"
"поперек"
"несмотря на"
"в течение"
"превыше"
"за исключением"
"противно"
"обо"
"вроде"
"насчет"
"вслед"
"сверху"
"навстречу"
"сзади"
"спустя"
"поверх"
"окрест"
"внутрь"
"помимо"
"изъ"
"черезъ"
"передъ"
"безъ"
"свыше"
"на борту"
"на борт"
"соответственно"
"в соответствии с"
"сродни"
"ранее"
"вблизи"
"в честь"
"по мотивам"
"что касается"
"касательно"
"по сравнению с"
"взамен"
"до тех пор пока"
"наперекор"
"в случае"
"на случай"
"с помощью"
"в поисках"
"в свете"
"от лица"
"вплоть"
"во время"
"ввиду"
"чрез"
"наподобие"
"посередине"
"посредине"
"исключая"
"промеж"
"послѣ"
"вна"
"не считая"
"за вычетом"
])


(setq slovarik-predicatives-defs [

"(+ prepositional case) about, of, on, {literary} (+ accusative case) against, upon"
"with {i|+ {glossary|instrumental}}, from, off, from off, from below {i|with abstract nouns; nouns entailing a flat, open area; and special exceptions; + {glossary|genitive}}, because of, since {i|expressing a cause of motivation; + {glossary|genitive}}, for, about {i|indicating indefinite time or number} {i|+ {glossary|accusative}}, from {i|indicating a duration of time; + {glossary|genitive}}, with {i|in certain time expressions; + {glossary|instrumental}}"
"''(location)'' in, at, on {+obj|prep}, ''(direction)'' to, into {+obj|acc}, ''(time)'' at, in, on {+obj|acc}, per"
"at, by, near, in the possession of {qualifier|used to express 'to have'}"
"{non-gloss definition|with accusative case},  up to,  till,  {non-gloss definition|indicates distribution (with numerals other than one, a thousand, a million, a billion, a trillion, etc. and compound numerals ending these words)}, {non-gloss definition|with dative case},  over, {non-gloss definition|with prepositional case},  on, immediately after,  for"
"with ''(+ instrumental case)'', off, from ''(+ genitive case)''"
"to, towards, ''(time)'': by, for"
"for"
"from, out of, of, through"
"{q|+ prepositional case} about, of, on, {q|+ accusative case} against, upon"
"{location} in, at, on ''(+ prepositional case)'', {direction} to, into ''(+ accusative case)'', {time} at, in, on"
"{+accusative} onto, on, {+accusative} {qualifier|places, only certain nouns} nearby, by (in the sense of near). Interchangable with у#Russian|у (which requires genitive case)., {+accusative} to, toward, {+accusative} to set out for (in the sense 'to start an activity with the intention of finishing it'), to go for, {+accusative} {qualifier|duration, value, purpose} for, {+accusative} about, for, {mathematics|+accusative} over; by; divided by, {+accusative} {qualifier|time} in, for, {+accusative} {qualifier|time} in, for, {+prepositional} on, upon, {+prepositional} {qualifier|only with certain nouns} in, at, {+prepositional} using a means of transport to get somewhere (while в#Russian|в is just 'to be in something'), {+prepositional} runs/operates only because of someone/something; works on, runs on, {+prepositional} is assigned to, {+prepositional} with, for, {neologism|+prepositional} being dominated by a certain emotional state, {neologism|+prepositional} accomplishing something while being dominated by a certain emotional state '''and''' primarily because of it"
"before, up to, till, until, with respect to, concerning, regarding"
"from, since"
"without, minus"
"after (in time)"
"{n-g|with {glossary|accusative case}},  under ''(movement to beneath)'',  towards, to,  about, on the eve of ''(time)'',  in imitation of, à la,  for, suitable as, {n-g|with {glossary|instrumental case}},  under, below, beneath ''(location)'',  near, by,  used for"
"against, opposite"
"{ru-abbrev of|вме́сто||instead of}"
"including"
"including"
"near, about"
"{l|en|from} (behind), {l|en|over}, {l|en|because of}"
"(of location) behind; beyond; on the other side of {case-gov|instrumental}, (of motion, ''+ accusative case'') to, (of time, ''+ accusative case'') during {close to в течение}, (of time, + accusative case with до) time before an event, (''+ accusative case'') for; to; by; after; over, (''+ accusative case'') instead of, (of voting, ''+ accusative case'') in favor of, (''+ instrumental case'') at; while, {qualifier|used in expressions}"
"near, around, about, by"
"before, previously to"
"through, across, over, ''(time)'' in, after, via, with, with the help of,  because of"
"near, in the vicinity of"
"instead of"
"past, by"
"beside, by, near"
"except, besides"
"round, around, about"
"along"
"in, inside, within (''position'')"
"in spite of, contrary to"
"from under, ''As a designation of former use'', from"
"out of, outside"
"{with instrumental|rarely|with genitive} between, among"
"between, among"
"above, over"
"{qualifier|variant of {m|над} before words beginning with certain awkward consonant clusters such as '''мн-'''} above, over"
"among, in the midst of (+ ''genitive case'')"
"among, in the midst of {i|+ {glossary|genitive}}"
"behind"
"beside, near"
"for the sake of"
"above, over, beyond"
"through"
"in front of, before, right/immediately before"
"in front of, before"
"{archaic|literary} in front of, before {qualifier|+ instrumental case}"
"in front of, before (+ instrumental case) ''(before awkward consonant clusters)''"
"in the middle of, in the midst of"
"about, concerning"
"in the presence of, in the time of, at, by"
"{alternative form of|под} {i|used before words beginning with certain awkward consonant clusters such as {m||мн-}, {m||вс-}, and {m||сн-}}"
"around"
"against, in spite of"
"opposite to, across the way"
"vis-à-vis"
"as a consequence (of)"
"vis-à-vis, as regards, with respect to"
"including"
"ago"
"from, since"
"{ru-pre-reform|с}"
"{ru-pre-reform|под}"
"{ru-pre-reform|к}"
"{ru-pre-reform|в}"
"{ru-pre-reform|над}"
"{ru-pre-reform|об}"
"{ru-pre-reform|от}"
"thanks to, owing to, through (by means of), due to"
"according to, as to"
"{alternative form of|из}"
"by means of, with the help of, per, via"
"|поперёк| across, athwart"
"in spite of, despite {qualifier|the action must be completed in advance}, notwithstanding, although"
"during, within"
"''(+ genitive)'' above"
"with the exception of, except, apart from"
"{obsolete} against"
"''(+ prepositional case)'': about, of, on, ''(+ accusative case)'': against, upon"
"like, such as, kind of, not unlike, similar to"
"|насчёт| {colloquial} concerning, about (+ genitive case|genitive)"
"after, behind, following"
"over, above"
"toward, towards"
"behind"
"after, later"
"over"
"around, near"
"into, inside {i|direction}"
"besides, aside from, apart from, in spite of, beside"
"{ru-pre-reform|из}"
"{ru-pre-reform|че́рез}"
"{ru-pre-reform|пе́ред}"
"{ru-pre-reform|без}"
"above {more}"
"aboard {on board}"
"aboard {on board}"
"according to, in accordance with"
"according to {based on statement}"
"akin {of the same kin; related by blood}"
"previous to {+preo|genitive}"
"around, near (+ genitive case)"
"after, in honour of (+ genitive case)"
"based (on) (a story), after"
"as for {regarding; about}, with regard to, as regards, in regard to, with respect to, in relation to, with reference to, in the matter of"
"concerning, regarding (+ genitive case)"
"as compared with, as opposed to, in contrast with, against, versus, over against, beside"
"against {in exchange for} (на (na) + accusative case)"
"while"
"counter"
"in case {in the event (of)}"
"in case {in the event (of)}"
"via, by dint of {by (means of); using (a medium)} (+ genitive case)"
"after {in pursuit of, seeking}"
"in light of, in the light of {given, considering}"
"on behalf of"
"up to, right up to, down to"
"during {within a given time interval}"
"in view of"
"{poetic} through; across, over"
"like, not unlike"
"in the middle"
"{alternative form of|посереди́не}"
"except {i|+{glink|accusative}}"
"{dated|or|colloquial} between, among"
"{ru-pre-reform|после}"
"in"
"not counting, apart from, exclusive of, less"
"less, minus, deducting, with the deduction (of); except for, apart from"
])

