(setq slovarik-wordlist [

"м"
"с"
"г"
"д"
"да"
"не"
"на-"
"с-"
"до-"
"за-"
"над-"
"воз-"
"из-"
"без-"
"в-"
"вы-"
"низ-"
"о-"
"от-"
"пере-"
"по-"
"под-"
"у-"
"пре-"
"пред-"
"при-"
"про-"
"противо-"
"раз-"
"бес-"
"во-"
"вос-"
"вз-"
"взо-"
"вс-"
"ис-"
"изо-"
"надо-"
"нис-"
"об-"
"обо-"
"ото-"
"подо-"
"рас-"
"со-"
"цис-"
"мк"
"мг"
"разо-"
"пра-"
"дека-"
"авиа-"
"тетра-"
"анти-"
"полу-"
"пол-"
"анархо-"
"квази-"
"кибер-"
"контр-"
"нано-"
"вне-"
"афро-"
"евро-"
"англо-"
"германо-"
"франко-"
"архи-"
"авто-"
"само-"
"себе-"
"аудио-"
"электро-"
"ко-"
"взаимо-"
"одно-"
"едино-"
"уни-"
"много-"
"мульти-"
"вице-"
"мини-"
"макро-"
"теле-"
"не-"
"трех-"
"четырех-"
"прото-"
"рос-"
"сов-"
"фото-"
"гидро-"
"суб-"
"двух-"
"дву-"
"ди-"
"тре-"
"три-"
"микро-"
"ультра-"
"сверх-"
"нео-"
"инфра-"
"супер-"
"экстра-"
"радио-"
"видео-"
"техно-"
"кое-"
"после-"
"пост-"
"Санкт-"
"турбо-"
"интер-"
"между-"
"меж-"
"зепто-"
"милли-"
"кило-"
"мега-"
"гига-"
"йокто-"
"аэро-"
"деци-"
"гео-"
"зоо-"
"недо-"
"низо-"
"благо-"
"все-"
"наи-"
"еже-"
"пона-"
"экс-"
"через-"
"четверо-"
"роз-"
"па-"
"су-"
"мото-"
"черес-"
"чрез-"
"гекто-"
"внутри-"
"русско-"
"гипер-"
"кино-"
"псевдо-"
])


(setq slovarik-wordlist-defs [

"{ru-abbrev of|милли-||milli-} {qualifier|(0.001)}"
"centi- {0.01}"
"hecto- {x 100}"
"d, deci- (0.1)"
"da, deca- (x 10)"
"{With prepositions and pronouns '''не''' actually is a prefix, in spite of the fact that it is written separately.}"
"{used with verbs} onto, upon, {used with verbs} to repletion, to satiation, to the full, enough, too much, {used with verbs} a quantity of, a lot of"
"{used with verbs} {describing an action moving from a single position or many positions into another single position}, {used with verbs} down {describing a downward action}, {used with verbs} off, from off {describing an action of removing oneself to another location}"
"{used with verbs} up to, {used with verbs} completely {describing a completion of an action to its end}"
"{used with verbs} behind, beyond, {used with verbs} to begin doing {describing an action of commencing}, {used with verbs} in advance {describing an action of doing something ahead of time}, {used with verbs} {n-g|perfectivizes verbs}, {used with verbs} to the finish, to the end {describing a completed result}, {used with verbs} {n-g|describing an action of covering something, of being covered, or hiding behind something}, {used with verbs} {n-g|describing an intensified or extreme action or an action of doing something up to the point that an object becomes a junk}, {used with verbs} {n-g|describing an action that implies the existence of barriers, obstacles, or hindrance}, {with a reflexive verb} to do with abandonment, {used with nouns, in place names} trans-"
"{n-g|takes verbs, produces verbs}: to extend, add, {n-g|takes verbs, produces verbs}: to apply an action or measure, {n-g|takes verbs, produces verbs}: to apply an action in incomplete manner, {n-g|takes verbs, produces verbs}: super-, {n-g|takes nouns, produces nouns and adjectives}: over, above"
"{used with verbs} upwards, up, {used with verbs} returning, re-"
"out from, {n-g|When added to a verb, it may form a verb with a sense of completeness, abundance or exhaustion.}, {n-g|When added to a verb, it may form a verb with a sense of destruction, ruined due to use.}, {n-g|When added to nouns, especially when they have the suffix -ье, it indicates location of an object.}, {n-g|When added to adjectives for colours, an adverb is formed indicating nuance.}, {n-g|When added to nouns, it may form an adverb indicating spatial or temporal properties. Usually in archaic or highly formal style.}, {n-g|When added to adverbs, it can form an adverb with a sense of direction for an action.}"
"dis-, un-, -less"
"in, into {describing an action of moving inside of something or moving deeper into something}"
"{used with verbs} out, out from {describing an action of moving outside from inside}, {used with verbs} completion or fulfillment"
"down, de-"
"{n-g|prefix added to adjectives or nouns to produce {glossary|factitive} verbs in conjunction with {m|-ить}, i.e. verbs with the meaning of making (someone or something) the mentioned characteristic or property}, {n-g|prefix added to adjectives or nouns to produce {glossary|fientive} verbs in conjunction with {m|-ить} + {m|-ся} or with {m|-еть}, i.e. verbs with the meaning of becoming or receiving the mentioned characteristic or property}, {n-g|prefix added to verbs of motion}: about, around, {n-g|prefix added to nouns}: close by, around, {n-g|prefix added to verbs}: completely, to the full extent, {n-g|prefix added to verbs, with the suffix {m|-ся}}: to fail at (some action), {n-g|prefix added to verbs, with the suffix {m|-ся}}: to recover from (some action)"
"{used with verbs} away from"
"{used with verbs} over, over again {describing an action of moving by overcoming one or more obstacles}, {used with verbs} across, trans- {describing an action of moving to a different place}, {used with verbs} too much {describing an action of resulting something excessive}, {used with verbs} extremely {describing an action of doing something much more extreme than an average action}, {used with verbs} re- {describing a repeating action}, {used with verbs} {n-g|describing an alternating or exchanging action}, {used with verbs} {n-g|describing a consequence of a completed action that affects many entities of a group}, {used with verbs} {n-g|describing a destructed state of an entity, usually by cutting or tearing with tools or tool-like implements}, {used with verbs|colloquial|rare} {n-g|describing a light action that is not done in full measure}"
"perfective aspect, {rare} imperfective aspect, for a while, a little {see w:delimitative aspect|delimitative aspect}, place names"
"{used with verbs} upwards {describing an action of moving from the bottom up}, {used with verbs} closer {describing an action of approaching to an entity}, {used with verbs} adding {describing an action of adding more entity}, {used with verbs} {describing a meaning that shows a finished action or an obtainment of a result}, {used with verbs} {describing an action of copying or following someone's action}, {used with verbs} {describing an existence of the certain action that is weak, invisible, hidden or incomplete}, {n-g|takes nouns, produces nouns or adjectives}: under-, sub- {referring to literal position under something, being under the influence of something, occupying a title or position below a superior, etc.}, {n-g|takes adjectives, produces adverbs}: completely"
"away, with a more concrete purpose"
"{used with verbs} over, across, {used with adjectives} most, very {qualifier|superlative degree}"
"{used with verbs} before, fore-, pre-, cis- (in place names)"
"{used with verbs} arrival, {used with verbs} attachment, on, {used with verbs} adding to, {used with verbs} slightly, partially, {place names} by, near, next to"
"{used with verbs} through, past {describing an action of passing through a space or an object}, {used with verbs} {n-g|describing an action of covering a whole object}, {used with verbs} {n-g|describing an action of passing by an entity and moving further from an entity}, {used with verbs} {n-g|describing an action that entails completeness, exhaustiveness, or accuracy}, {used with verbs} {n-g|describing a momentary action with a short duration}, {used with verbs} {n-g|describing an action that lasts for a certain period of time}, {used with verbs} {n-g|describing an action that describes losses, expenses, wasting, or forgetting}, {used with nouns} {n-g|describing a state of being that is located between two entities or among more than two entities}, {used with adjectives or nouns} {n-g|describing an initial appearance or insufficiency of characteristics}"
"counter, anti-"
"{used with verbs} asunder, apart, {used with verbs} dis-, di-, un-, {used with verbs} enlarged action, {used with verbs} with reflexives, giving rein to, {used with verbs|in the negative} not quite"
"{alternative form of|без-}"
"{alternative form of|в-} {i|used before certain consonant clusters}"
"{alternative form of|воз-} {i|used before a voiceless consonant}"
"{used with verbs} upwards, up, {used with verbs} returning, re-"
"{alternative form of|вз-} {i|used before certain consonant clusters}"
"{alternative form of|вз-} {i|used before voiceless consonants}"
"{alternative form of|из-}"
"{alternative form of|из-} {i|used before certain consonant clusters}"
"{alternative form of|над-} {i|used before certain consonant clusters}"
"{alternative form of|низ-} {i|before voiceless consonants}"
"{alternative form of|о-} {qualifier|before certain letters}"
"{alternative form of|об-} {i|used before certain consonant clusters}"
"{alternative form of|от-} {i|used before certain consonant clusters}"
"{alternative form of|под-} {i|used before certain consonant clusters}"
"{alternative form of|раз-} {i|before voiceless consonants}"
"{alternative form of|с-} {i|used before certain consonant clusters}, with, con-, co-"
"{chemistry} cis-"
"micro- {0.000001}"
"M, mega- {x 1,000,000}"
"{alternative form of|раз-} {i|used before certain consonant clusters}"
"great {i|when used with ancestors and descendants}, ur-, proto- {primitive, original}"
"deca- (x10)"
"air|air-, aero-"
"tetra-"
"anti-"
"{highly|_|productive|takes nouns|produces compound nouns} semi-, demi-, half-ref{Русская грамматика|551.г}/ref, {highly|_|productive|takes nouns in genitive case|produces compound nouns} semi-, demi-, half- {n-g|paired with пол- form}ref{Русская грамматика|552}/ref, {takes adjective|produces compound adjective} semi-, demi-, half-ref{Русская грамматика|756.4}/ref, {productive|takes verbs|produces compound verbs} {n-g|incompletely}ref{Русская грамматика|960.1}/ref, {takes adverb|produces compound adverb} {n-g|incompletely}ref{Русская грамматика|1026}/ref"
"{alternative form of|полу-}, {senseid|time}{takes ordinal adjective in genitive case|produces compound nouns} half past"
"anarcho- (denoting anarchy or anarchism)"
"pseudo-"
"cyber- {the Internet or cyberspace}"
"counter- {in opposition to}"
"nano- {1 000 000 000th part of}, nano- {nanotechnology industry}"
"extra- {outside, beyond}"
"Afro- {African}"
"Euro- {related to Europe}"
"Anglo- {relating to England or English}"
"Germano-, German {of Germany}"
"Franco-, French {of France}"
"archi-, arch- {chief, highest, most extreme}"
"auto-, self- {regarding oneself}, auto- {automatic}, auto- {relating to cars or the driving of cars}"
"auto-, self- {regarding oneself}"
"auto- {regarding oneself}"
"audio {of or relating to audible sound}"
"electro- {meaning electricity or electrical}"
"co- {together, mutually, jointly}"
"co- {together, mutually, jointly}"
"{l|en|uni-} {one}"
"uni- {one}"
"uni- {one}"
"multi- {pertaining to many}"
"multi- {pertaining to many}"
"vice- {deputy}"
"mini- {a smaller than usual version of an item}"
"macro-"
"tele- {over a distance; relating to television}"
"un-, non-, in-, im-, ir-, dis-, mis- {not}"
"|трёх-| tri-, triple {three}"
"|четырёх-| quadri-, tetra-, four-"
"proto- {first}"
"{n-g|Stressed equivalent of {m|рас-}. Found primarily in deverbal nouns.}, Russian (used in the names of companies or organizations)"
"Soviet (used in the names of companies or organizations)"
"photo- {light}"
"hydro- {pertaining to water}"
"sub- {under, beneath}"
"bi-, di-, duo- {two, twice, double}"
"bi-, di-, duo- {two, twice, double}"
"di- {two, twice, double}"
"tri-, tre- {three}"
"tri-, tre- {three}"
"micro- {very small}, micro- {one millionth}"
"ultra- {excessively, to an extreme}"
"extra-, over-, super-, ultra-"
"neo- {new}"
"infra- {below, beneath, inferior}"
"super-"
"extra-"
"radio- {radiation; radio (broadcasting)}"
"video- {related to moving images, and especially to television}"
"techno- {used to form words relating to technology}"
"(expresses indefiniteness) some, some-"
"post-, after-"
"post- {later}"
"St {saint}"
"turbo-"
"inter- {among, between}"
"inter- {among, between}"
"inter- {among, between}"
"zepto- {10−21}"
"milli-"
"kilo-"
"mega-"
"giga-"
"yocto- {10−24}"
"aero-, air {referring to air or (usually) aircraft}"
"deci- {10-1}"
"geo- {Earth}"
"zoo- {pertaining to animals}"
"{used with verbs} under-, insufficiently, {used with verbs} to fail to do"
"{alternative form of|низ-} {i|used before certain consonant clusters}"
"good|good-, well|well-"
"all-, omni-, pan-"
"{n-g|Prefix forming {glink|superlative}s from {glink|comparative} adjectives (or nonstandardly from positive adjectives)}."
"once a ... {occurring once in a given time period}"
"{used with verbs}, {used with verbs} a quantity of, a lot of., {pejorative|colloquial|productive|used with verbs} to indicate meaningless action"
"{productive|in journalistic style|occasional|or|colloquial|takes nouns|produces nouns} ex- {former}ref{R:ru:Grammar80|498}/ref, {unproductive|takes adjective|produces adjective} extra- {out of; outside}ref{R:ru:Grammar80|719}/ref"
"{n-g|Adjectival and nominal prefix, used in specialized terminology, slightly productive}: trans-, cross-, {n-g|Adjectival and nominal prefix, used in specialized terminology, slightly productive}: alternating"
"{l|en|quadri-}, {l|en|tetra-} {four}"
"{n-g|Stressed equivalent of {m|раз-}. Found primarily in deverbal nouns and past passive participles.}"
"near-, pseudo-, step-"
"com-, con- {non-gloss definition|(forms nouns denoting a connection or link)}, {non-gloss definition|(forms nouns denoting incompleteness)}"
"motor {referring to something motorized}"
"{n-g|Adjectival and nominal prefix, used in specialized terminology, slightly productive}: trans-, cross-, {n-g|Adjectival and nominal prefix, used in specialized terminology, slightly productive}: alternating"
"over-, trans-"
"hecto-"
"intra-"
"Russo-"
"hyper-#English|hyper-"
"cinema; film; movie"
"pseudo-"
])

