(setq slovarik-pronouns [

"я"
"весь"
"она"
"ее"
"мой"
"мы"
"они"
"оно"
"ты"
"вы"
"твой"
"ваш"
"наш"
"его"
"свой"
"себя"
"самый"
"что"
"што"
"который"
"кто"
"многие"
"немногие"
"сколько"
"сей"
"се"
"столько"
"несколько"
"что-либо"
"кто-либо"
"кто-нибудь"
"что-нибудь"
"что-то"
"кто-то"
"друг друга"
"многое"
"нечего"
"некого"
"нею"
"сколькие"
"ничего"
"кое-кто"
"никто"
"шо"
"нечто"
"где-нибудь"
"ничто"
"как-нибудь"
"то же, что"
"самъ"
"онъ"
"некто"
"чей-либо"
"некоторый"
"где-то"
"некий"
"всякий"
"кое-что"
"кое-какой"
"никакой"
"тя"
"оне"
"сие"
"хто"
"таков"
"каков"
"Вы"
"всѣ"
"ея"
"чего"
"че"
"ни крошки"
"чей-нибудь"
"ничей"
"чей-то"
"какой-то"
"какой-нибудь"
"какой-либо"
"ею"
"ся"
"этакий"
"собою"
"чо"
"кое-чей"
"сколько-то"
"сколько-нибудь"
"тот-то"
"какой-никакой"
"все-все"
"все-все"
"столечко"
"одно и то же"
"ниче"
"иже"
"тащя"
])


(setq slovarik-pronouns-defs [

"{l|en|I} {first-person singular subject pronoun}"
"all, the whole, the whole of, everything, all, everybody, everyone"
"she, it {i|third-person feminine singular pronoun}"
"|её| {possessive pronoun} her, its"
"{possessive pronoun} my, mine"
"we, I {only when used with {m|с}}"
"they {i|third-person plural pronoun}"
"it {i|third-person neuter singular pronoun}"
"{familiar} second-person singular, nominative case: you, thou"
"you {i|plural or formal}"
"{possessive pronoun} your, yours, thy, thine ''(2nd-person familiar, singular only)''"
"{possessive} your, yours {q|2nd-person singular formal or 2nd-person plural}"
"{possessive} our, ours, {colloquial} Russian; produced, manufactured ''etc.'' in Russia"
"{possessive pronoun} his, {possessive pronoun} its"
"{reflexive-possessive pronoun} one's own; my, his, her, its, our, your, their ''(always refers to the subject of the sentence)'', peculiar"
"''(reflexive pronoun)'' myself, yourself, himself, herself, itself, ourselves, yourselves, themselves (no nominative case), ''(reflexive pronoun)'' oneself"
"{lb|de|definitive} the very, the selfsame, the very same, the most {gl|superlative degree}"
"{interrogative} what, {nonstandard|relative} that, which"
"{misspelling of|что}"
"{interrogative} which?, {relative pronoun} which, that, who"
"''(relative pronoun)'' who, ''(interrogative pronoun)'' who"
"many (people)"
"few, a few, some, several"
"how much, how many, so much, so many, how long"
"{archaic|poetic|literary|humorous} this, this here"
"|сё| {archaic} {inflection of|сей||nom|n|s}: this, this here, {archaic} {inflection of|сей||acc|n|s}: this, this here"
"this/that much/many, so much, so many"
"a few, several, some (+ genitive)"
"''(indefinite pronoun)'' anything, something"
"anybody, anyone, somebody, someone"
"''(indefinite pronoun)'' anybody, anyone, someone or other"
"''(indefinite pronoun)'' anything"
"''(indefinite pronoun)'' something"
"{indefinite|_|pronoun} somebody, someone"
"one another, each other"
"{in singular} many things, many a thing, much"
"there is nothing to (negative genitive of {m|что}), there is no need, (one) need not, (it is) no use"
"there is no one to (negative genitive of {m|кто})"
"{dated|poetic||or|dialectal} {inflection of|она́||ins}"
"how much, how many, so many (obsolete form of сколько, used as adjective or without a following noun)"
"nothing (genitive of the indefinite pronoun {m|ничто́}...the nominative is rarely used, and the genitive is preferred)., {colloquial} so-so, not bad, pretty, never mind!; that's all right!; no problem!"
"{indefinite pronoun} someone, somebody, one or two people, some people, a few people"
"''(indefinite pronoun)'' nobody, no one; ''(with negative)'' anybody, anyone"
"{low|_|colloquial|non-standard|proscribed|Ukraine|South Russia} what, {alternative form of|что|nocap=1}"
"something"
"{non-gloss definition|indefinite pronoun}, anywhere, somewhere"
"''(indefinite pronoun)'' nothing"
"''(indefinite pronoun)'' somehow, somehow or other, anyhow, ''(indefinite adverb)'' sometime"
"same as, same thing as"
"{ru-pre-reform|сам}"
"{ru-pre-reform|он}"
"{non-gloss definition|indefinite pronoun}, somebody, someone, a certain"
"''(indefinite pronoun)'' somebody's, someone's"
"some; certain {i|adjectival}, {plural only} some, some people; certain people {i|pronominal}"
"{non-gloss definition|indefinite pronoun}, somewhere"
"a certain, certain, some"
"anybody, anyone, everybody, everyone, anything"
"something, some things, a little"
"some, any"
"''(indefinite pronoun)'' not any of possible variants, no, none; (in a negative context) whatever, whatsoever, absolutely, {slang} (about person's state) inactive, senseless, e.g. very drunken or exhausted"
"{colloquial} {contraction of|тебя́}"
"{archaic} they {i|feminine only}"
"{archaic} {inflection of|сей||nom|n|s}, {archaic} {inflection of|сей||acc|n|s}"
"{proscribed|low|_|colloquial|non-standard|Ukraine|Belarus|South Russia} who, non-standard form of {m|кто}"
"such"
"how, what, what kind, what sort of, as, such as"
"{alternative case form of|вы} - you (polite, {g|s} and {g|p})"
"{ru-pre-reform|все}"
"{ru-pre-reform|её}"
"{colloquial} {inflection of|что||nom}, {colloquial} {inflection of|что||acc}, {colloquial} why? {non-gloss definition|(never used on its own, only in a sentence)}"
"|чё| {non-standard|low|_|colloquial|proscribed} {contraction of|чего|чего́}, {non-standard|low|_|colloquial|proscribed} {contraction of|что}"
"none, nothing"
"anybody's {belonging to anybody; possessive form of anybody}"
"nobody's {belonging to nobody (possessive form of nobody)}"
"somebody's {belonging to somebody (possessive form of somebody)}"
"some, {l|en|a}/{l|en|an} {certain, unspecified or unknown}, a kind of, a sort of; something like"
"some, any, some (no more than); (only) about"
"some, any"
"{dated|poetic||or|dialectal} {inflection of|она́||ins}"
"{colloquial} {contraction of|себя́}"
"{colloquial} such, like this, {colloquial} what (a)"
"{qualifier|less common} {inflection of|себя́||ins}"
"{colloquial|non-standard} what, {alternative form of|что|nocap=1}, {alternative form of|чё|nocap=1}"
"somebody's, someone's"
"some, a few; any (in a question), a little, to (at least) some extent"
"some, a few; any, anything (in a question)"
"(emphasised) that (one), so and so {i|often duplicated after {m|и}}"
"{colloquial} at least some sort of"
"{colloquial} absolutely everyone"
"|всё-всё| {colloquial} absolutely everything"
"{diminutive of|сто́лько}"
"the same thing, the same, one and the same"
"|ничё| {non-standard|low|_|colloquial|proscribed} {contraction of|ничего́}"
"{archaic|ecclesiastic|or|literary} which; et cetera"
"{alternative form of|таща́|nocap=1}, {ru-participle of|тащи́ть||pres|adv|impfv}"
])

